name: Test EC2 Connection with GHA

on:
  workflow_dispatch:

jobs:
  test-ec2-connect:
    name: test ec2 connection
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH Directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Make Private Key File
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Test SSH Connect to EC2
        env:
          HOSTNAME: 13.125.218.128
          USER_NAME: ubuntu
        run: |
          echo "SSH 연결 시도 중..."
          ssh -vvv -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2_key \
            ${USER_NAME}@${HOSTNAME} \
            'echo 현재 사용자: $(whoami)'
            'echo 호스트명: $(hostname)'
          echo "연결 테스트 종료"

      - name: Cleanup Private Key
        if: always()
        run: |
          rm -rf ~/.ssh/ec2_key
